[NezhaMonitoring]
other = "Nezha Monitoring"

[Server]
other = "Servers"

[Services]
other = "Services"

[Task]
other = "Tasks"

[Notification]
other = "Notifications"

[Settings]
other = "Settings"

[Home]
other = "Home"

[BackToHomepage]
other = "Back to home"

[AdminPanel]
other = "Admin"

[Logout]
other = "Log out"

[Login]
other = "Log in"

[ConfirmLogout]
other = "Confirm Logout?"

[AfterLoggingOutYouHaveToLoginAgain]
other = "You must log in before accessing the admin area"

[Cancel]
other = "Cancel"

[Confirm]
other = "Confirm"

[AddScheduledTasks]
other = "Add Schedule Task"

[Name]
other = "Name"

[Scheduler]
other = "Cron Expression"

[BackUp]
other = "Backup"

[3amDaily]
other = "(Every day at 3 o'clock)"

[Command]
other = "Command"

[Coverage]
other = "Coverage"

[IgnoreAllAndExecuteOnlyThroughSpecificServers]
other = "Ignore All, Only execute by specific servers"

[AllIncludedOnlySpecificServersAreNotExecuted]
other = "Cover All, Only ignore specific servers"

[ExecuteByTriggerServer]
other = "Only servers that are included in the notification rule"

[SpecificServers]
other = "Specific Servers"

[EnterIdAndNameToSearch]
other = "Input Server ID/Name to search"

[NotificationMethodGroup]
other = "Notification Group"

[PushSuccessMessages]
other = "Send Success Notification"

[TaskType]
other = "Task Type"

[CronTask]
other = "Scheduled task"

[TriggerTask]
other = "Trigger task"

[TheFormaOfTheScheduleIs]
other = "The Cron Expression is like:"

[SecondsMinutesHoursDaysMonthsWeeksSeeDetails]
other = "sec min hour day month week, details in "

[ScheduleExpressionFormat]
other = "CRON Expression Format"

[IntroductionOfCommands]
other = "Command: Just like writing shell/bat scripts, but line wrap is not recommended. Multiple Commands should be connected with <code>&&</code>/<code>&</code>. Command not found may cause by missing <code>PATH</code> environment variable, for <code>Linux</code> Server, you may try adding <code>source ~/.bashrc</code> at beginning of your command or execute by absolute path."

[AddMonitor]
other = "Add Service Monitor"

[Blog]
other = "Blog"

[Target]
other = "Target"

[Type]
other = "Type"

[SslExpirationOrChange]
other = "(SSL Certificate Expired/Changed)"

[Duration]
other = "Interval"

[Seconds]
other = "Seconds"

[EnableFailureNotification]
other = "Enable Failure Notification"

[FailureNotification]
other = "Incident Notification"

[MaxLatency]
other = "Max Latency (ms)"

[MinLatency]
other = "Min Latency (ms)"

[EnableLatencyNotification]
other = "Enable Latency Notifications"

[LatencyNotification]
other = "Latency Notification"

[IntroductionOfMonitor]
other = """
Input URL(With http/https prefix) for type <b>HTTP-GET</b>, SSL Certificate will be monitored automatically when URL has https prefix;<br>
Input hostname/IP for type <b>ICMP-Ping</b>: example.com;<br>
Input hostname/IP:Port for type <b>TCP-Ping</b>: example.com:22;"""

[AddNotificationMethod]
other = "Add Notification Method"

[Tag]
other = "Notification Group"

[DoNotSendTestMessages]
other = "Do Not Send Test Message"

[RequestMethod]
other = "Request Method"

[RequestType]
other = "Request Type"

[VerifySSL]
other = "Verify SSL"

[AddNotificationRule]
other = "Add Notification Rule"

[Rules]
other = "Rules"

[NotificationTriggerMode]
other = "Mode of triggering notification"

[ModeAlwaysTrigger]
other = "Always triggered"

[ModeOnetimeTrigger]
other = "Triggered only once"

[EnableTriggerTask]
other = "Enable trigger tasks"

[FailTriggerTasks]
other = "Tasks to be triggered in case of failure"

[RecoverTriggerTasks]
other = "Tasks to be triggered after fault recovery"

[Enable]
other = "Enable"

[AddServer]
other = "Add Server"

[BatchEditServerGroup]
other = "Batch Modify Groups"

[BatchDeleteServer]
other = "Batch Delete Server"

[InputServerGroupName]
other = "Enter the name of the group"

[ServerGroup]
other = "Server Group"

[EinsteinLightspeed1]
other = "Einstein Light Speed 1"

[DisplayIndex]
other = "Display Index"

[TheLargerTheNumberTheHigherThePriority]
other = "Greater numbers will be displayed first"

[Secret]
other = "Secret"

[Note]
other = "Note"

[LinuxOneKeyInstall]
other = "One-click installation on Linux"

[NoDomainAlert]
other = "Set CDN bypassed Domain/IP in setting before using this function"

[PushSuccessfully]
other = "Send Success Notification"

[LastExecution]
other = "Last run on"

[LastResult]
other = "Last Result"

[Administration]
other = "Manage"

[CoverAll]
other = "Cover All"

[IgnoreAll]
other = "Ignore All"

[ByTrigger]
other = "Execute when triggered"

[DeleteScheduledTask]
other = "Delete Scheduled Task"

[ConfirmToDeleteThisScheduledTask]
other = "Confirm Delete?"

[AccessDenied]
other = "Access Denied"

[Use]
other = "Use"

[AccountToLogin]
other = "account to login"

[SignUp]
other = "Sign up"

[DontHaveAnAccount]
other = "Don't have an account yet?"

[SSLCertificate]
other = "HTTP(S)/SSL Certificate"

[TCPPort]
other = "TCP Port"

[DeleteService]
other = "Delete Service Monitor"

[ConfirmToDeleteThisService]
other = "Confirm Delete?"

[DeleteNotificationMethod]
other = "Delete Notification Method"

[ConfirmToDeleteThisNotificationMethod]
other = "Confirm Delete?"

[ForceUpdate]
other = "Force Update"

[SelectAll]
other = "Select All"

[VersionNumber]
other = "Version"

[OneKeyInstall]
other = "One-click installation"

[ClickToCopy]
other = "Click To Copy"

[DeleteServer]
other = "Delete Server"

[ConfirmToDeleteServer]
other = "Confirm Delete?"

[NoServerSelected]
other = "No Server Selected"

[ExecutionResults]
other = "Execute Results"

[SiteTitle]
other = "Site Title"

[AdministratorList]
other = "Admin List"

[Theme]
other = "Theme"

[CustomCodes]
other = "Custom code (style, script)"

[AccessPassword]
other = "Access Password"

[PanelServerDomainAndIP]
other = "CDN Bypassed Domain/IP"

[IPChangeAlert]
other = "IP Change Notification"

[AllIncludedOnlySpecificServersAreNotAlerted]
other = "Cover All, Only ignore specific servers"

[IgnoreAllOnlyAlertSpecificServers]
other = "Ignore all, cover only specific servers"

[IgnoreAllRequestOnlyThroughSpecificServers]
other = "Skip All Servers, Only send requests via specific servers"

[AllIncludedOnlySpecificServersAreNotRequest]
other = "Send requests from All servers, Only skip specific servers"

[ServerIDSeparatedByCommas]
other = "Server ID, separated by comma"

[IPChangeNotificationTag]
other = "Send Notification To Specific Notification Group"

[NotificationMessagesDoNotHideIP]
other = "Do NOT hide the IP in the notification"

[Save]
other = "Save"

[ModifiedSuccessfully]
other = "Modified successfully"

[TerminalConnectionTimeOutOrSessionEnded]
other = "Terminal connection timeout or session ended"

[TerminalConnectionFailed]
other = "Terminal connection failed, check reverse proxy for WebSocket connection on /terminal/* path"

[Default]
other = "Default"

[Offline]
other = "Offline"

[Platform]
other = "Platform"

[DiskUsed]
other = "Disk"

[MemUsed]
other = "RAM"

[SwapUsed]
other = "Swap"

[NetTransfer]
other = "Transfer"

[Load]
other = "Load"

[ProcessCount]
other = "Processes Count"

[ConnCount]
other = "Connections Count"

[BootTime]
other = "Boot Time"

[LastActive]
other = "Last Active"

[Version]
other = "Version"

[NetSpeed]
other = "Network"

[Uptime]
other = "Uptime"

[ServerIsOffline]
other = "Server is offline"

[Day]
other = "Days"

[RealtimeChannelEstablished]
other = "Real-time Channel Established"

[GetTheLatestMonitoringDataInRealTime]
other = "You can get the latest monitoring data in real-time!"

[RealtimeChannelDisconnect]
other = "Real-time Channel Disconnect"

[CanNotGetTheLatestMonitoringDataInRealTime]
other = "Unable to get the latest monitoring data in real-time!"

[30DaysOnline]
other = "Last 30 days availability"

[Details]
other = "Details"

[Status]
other = "Status"

[Availability]
other = "Availability"

[AverageLatency]
other = "Average delay"

[CycleTransferStats]
other = "Cycle Transfer Statistics"

[From]
other = "From"

[To]
other = "To"

[NextCheck]
other = "Next check"

[CurrentUsage]
other = "Current Usage"

[VerifyPassword]
other = "Verify Password"

[LightMode]
other = "Light Mode"

[DarkMode]
other = "Dark Mode"

[GridLayout]
other = "Grid Layout"

[ListLayout]
other = "List Layout"

[EnterPassword]
other = "Enter password"

[Location]
other = "Location"

[Running]
other = "Running"

[UpNetTransfer]
other = "Outbound"

[DownNetTransfer]
other = "Inbound"

[TotalUpNetTransfer]
other = "Total Outbound"

[TotalDownNetTransfer]
other = "Total Inbound"

[WrongPassword]
other = "Incorrect Password"

[AnErrorEccurred]
other = "An error occurred"

[SystemError]
other = "System Error"

[NetworkError]
other = "Network Error"

[ServicesStatus]
other = "Services Status"

[ServersManagement]
other = "Servers"

[ServicesManagement]
other = "Services"

[ScheduledTasks]
other = "Scheduled Tasks"

[ApiManagement]
other = "API"

[IssueNewApiToken]
other = "Add a token"

[Token]
other = "Token"

[DeleteToken]
other = "Remove Token"

[ConfirmToDeleteThisToken]
other = "Confirm remove this token?"

[YouAreNotAuthorized]
other = "You are not authorized"

[WrongAccessPassword]
other = "Wrong access password"

[Add]
other = "Add"

[Edit]
other = "Edit"

[AlarmRule]
other = "Alarm Rule"

[NotificationMethod]
other = "Notification Method"

[Incident]
other = "Incident"

[Resolved]
other = "Resolved"

[StatusDown]
other = "Failure"

[StatusNoData]
other = "No Data"

[StatusGood]
other = "Good"

[StatusLowAvailability]
other = "Low Available"

[ScheduledTaskExecutedSuccessfully]
other = "Task succeeded"

[ScheduledTaskExecutedFailed]
other = "Task Failed"

[IPChanged]
other = "IP Changed"

[Transleft]
other = "Data remaining"

[DashboardTheme]
other = "Admin Panel Theme"

[Info]
other = "Info"

[HideForGuest]
other = "No display to visitors"
